### ISSUE TITLE
There should be possibility to freed grid container width

### ISSUE THREAD

**Issue by adelura** [cksource/samples-framework#28]
For now it's not possible because of [this](https://github.com/cksource/samples-framework/blob/master/components/basicsample/core.less#L10-L13). We should introduce class like `freed-width` and modify selector to:

``` less
main .grid-container,
header .grid-container,
.navigation-a > div,
footer > div {
	overflow: hidden;

	&:not( .freed-width ) {
		max-width: 960px + 2 * @grid-gutter-width;
	}
}
```
