### ISSUE TITLE
Support for IE8

### ISSUE THREAD

**Issue by adelura** [cksource/samples-framework#31]
Didn't check all samples but at least documentation page layout is broken on IE8. Switcher: #13 also.

**Comment by oleq** [comment]
There's hardly anything broken there:
* some styles are not so fancy (i.e. border gradients),
* hljs does not start (we should disable it in IE8) in docs.
* `.freed-width` in `components/basicsample/core.less` cannot be used that way because IE8 does not support `:not()`:

    ```less
    &:not( .freed-width ) {
        max-width: 960px + 2 * @grid-gutter-width;
    }
    ```
   It breaks the layout of `samples/cke-basic` and derivatives. I don't know why `.freed-width` has been implemented in #28, anyway. There's no use-case for it.

It does not need to beautiful. It must work and we're very close to that level.
